from __future__ import annotations

KEYBOARD_LAYOUT_PRESETS: list[tuple[str, str]] = [
    ("English (United States)", "us"),
    ("English (US, International)", "us intl"),
    ("English (US, Alt. International)", "us altintl"),
    ("English (Dvorak)", "us dvorak"),
    ("English (Dvorak, Intl)", "us dvorak-intl"),
    ("English (Dvorak, Left-Handed)", "us dvorak-l"),
    ("English (Dvorak, Right-Handed)", "us dvorak-r"),
    ("English (Colemak)", "us colemak"),
    ("English (Colemak DH)", "us colemak-dh"),
    ("English (Workman)", "us workman"),
    ("English (Workman-International)", "us workman-intl"),
    ("English (United Kingdom)", "gb"),
    ("English (UK, Extended)", "gb extd"),
    ("English (UK, Intl)", "gb intl"),
    ("English (Scottish)", "gb scouse"),
    ("English (Irish)", "gb ie"),
    ("Brazilian Portuguese", "br"),
    ("Brazilian Portuguese (ABNT2)", "br abnt2"),
    ("Brazilian Portuguese (US)", "br us"),
    ("Portuguese (Portugal)", "pt"),
    ("Portuguese (Portugal, L)", "pt l"),
    ("Espanol (Latinoamerica)", "latam"),
    ("Espanol (Espana)", "es"),
    ("Espanol (Espana, cat)", "es cat"),
    ("Espanol (Espana, ast)", "es ast"),
    ("Espanol (Mexico)", "mx"),
    ("Francais (France)", "fr"),
    ("Francais (France, Legacy)", "fr legacy"),
    ("Francais (France, Bepo)", "fr bepo"),
    ("Francais (Canada)", "ca"),
    ("Francais (Canada, Multix)", "ca multix"),
    ("Francais (Switzerland)", "ch"),
    ("Francais (Belgium)", "be"),
    ("Deutsch (Germany)", "de"),
    ("Deutsch (Germany, Legacy)", "de legacy"),
    ("Deutsch (Germany, Neo)", "de neo"),
    ("Deutsch (Austria)", "at"),
    ("Deutsch (Switzerland)", "ch"),
    ("Italiano (Italy)", "it"),
    ("Italiano (Italy, Lay)", "it lay"),
    ("Italiano (Italy,  ergonomic)", "it ergo"),
    ("Nederlands (Netherlands)", "nl"),
    ("Nederlands (Belgium)", "be"),
    ("Polski (Poland)", "pl"),
    ("Polski (Poland, Legacy)", "pl legacy"),
    ("Polski (Poland, Programmer)", "pl prog"),
    ("Polski (Poland, Dvorak)", "pl dvorak"),
    ("Cestina (Czechia)", "cz"),
    ("Cestina (Czechia, Programmer)", "cz prog"),
    ("Slovencina (Slovakia)", "sk"),
    ("Magyar (Hungary)", "hu"),
    ("Magyar (Hungary, 101)", "hu"),
    ("Romanana (Romania)", "ro"),
    ("Romanana (Romania, Standard)", "ro std"),
    ("Romanana (Romania, Cedilla)", "ro cedilla"),
    ("Hrvatski (Croatia)", "hr"),
    ("Srpski (Serbia)", "rs"),
    ("Srpski (Serbia, Latin)", "rs latin"),
    ("Slovenscina (Slovenia)", "si"),
    ("Turkce (Turkey)", "tr"),
    ("Turkce (Turkey, F)", "tr f"),
    ("Turkce (Turkey, QWERTY)", "tr qwerty"),
    ("Ellinika (Greece)", "gr"),
    ("Ellinika (Greece, Extended)", "gr ext"),
    ("Russkiy (Russia)", "ru"),
    ("Russkiy (Russia, Typewriter)", "ru typewr"),
    ("Russkiy (Russia, Phonetic)", "ru phon"),
    ("Russkiy (Russia, Phonetic Wink)", "ru phon_wink"),
    ("Ukrainska (Ukraine)", "ua"),
    ("Ukrainska (Ukraine, Typewriter)", "ua typewr"),
    ("Ukrainska (Ukraine, Phonetic)", "ua phon"),
    ("Ukrainska (Ukraine, Homophonic)", "ua homophonic"),
    ("Bulgarian", "bg"),
    ("Bulgarian (Phonetic)", "bg phon"),
    ("Makedonski (Macedonia)", "mk"),
    ("Eesti (Estonia)", "ee"),
    ("Latvijas (Latvia)", "lv"),
    ("Latvijas (Latvia, apostrophe)", "lv apk"),
    ("Lietuvos (Lithuania)", "lt"),
    ("Lietuvos (Lithuania, Standard)", "lt std"),
    ("Lietuvos (Lithuania, Homophonic)", "lt homophonic"),
    ("Norsk (Norway)", "no"),
    ("Norsk (Norway, Sami)", "no smi"),
    ("Svenska (Sweden)", "se"),
    ("Svenska (Sweden, Sfd)", "se sefi"),
    ("Dansk (Denmark)", "dk"),
    ("Dansk (Denmark, Mac)", "dk mac"),
    ("Suomi (Finland)", "fi"),
    ("Suomi (Finland, Wink)", "fi wink"),
    ("Suomi (Finland, Mac)", "fi mac"),
    ("Islenska (Iceland)", "is"),
    ("Islenska (Iceland, Nordic)", "is nordic"),
    ("Japanese", "jp"),
    ("Korean", "kr"),
    ("Chinese (Pinyin)", "cn"),
    ("Chinese (Wubi)", "cn wubi"),
    ("Chinese (Cangjie)", "cn cangjie"),
    ("Vietnamese", "vn"),
    ("Arabic", "ara"),
    ("Arabic (Mac)", "ara mac"),
    ("Arabic (AZERTY)", "ara azerty"),
    ("Arabic (QWERTY)", "ara qwerty"),
    ("Hebrew", "il"),
    ("Hebrew (Phonetic)", "il phon"),
    ("Persian", "ir"),
    ("Persian (FA)", "ir fa"),
    ("Urdu (Pakistan)", "pk"),
    ("Urdu (Pakistan, CRULP)", "pk crulp"),
    ("Hindi (India)", "in"),
    ("Hindi (India, Inscript)", "in ben"),
    ("Hindi (India, PHNQ)", "in phoq"),
    ("Bengali (India)", "in ben"),
    ("Tamil (India)", "in tam"),
    ("Telugu (India)", "in tel"),
    ("Kannada (India)", "in kan"),
    ("Malayalam (India)", "in mal"),
    ("Marathi (India)", "in mar"),
    ("Gujarati (India)", "in guj"),
    ("Punjabi (India)", "in guru"),
    ("Thai", "th"),
    ("Thai (Pattachote)", "th pat"),
    ("Thai (TIS)", "th tis"),
    ("Georgian", "ge"),
    ("Georgian (Ergonomic)", "ge erg"),
    ("Armenian", "am"),
    ("Armenian (Phonetic)", "am phon"),
    ("Azerbaijani", "az"),
    ("Kazakh", "kz"),
    ("Kazakh (Russian)", "kz kazrus"),
    ("Uzbek", "uz"),
    ("Uzbek (Latin)", "uz lat"),
]
