#!/usr/bin/env bash

time=$(date +%Y-%m-%d-%I-%M-%S)
geometry=`xrandr | head -n1 | cut -d',' -f2 | tr -d '[:blank:],current'`
dir="$(xdg-user-dir PICTURES)/ScreenShots"
file="ShoT_${time}_${geometry}.png"

	if ! [ -d "$dir" ]; then
		mkdir -p $dir
	fi

function notify_view() {
	if [[ -e "$dir/$file" ]]; then
		notify-send -a "Screenshot" -i "$dir/$file" "Screenshot" "Screenshot saved"
	else
		notify-send -a "Screenshot" -i "$dir/$file" "Screenshot" "Screenshot deleted."
	fi
}

function imgtemp() {
	if [ "$bytes" ]; then
		echo "$bytes" | base64 --decode | tee "$file"
		notify_view
	else
		notify-send -a "Screenshot" -i ~/.config/i3/assets/cancel.svg "Screenshot" "Operation cancelled."
	fi
}

function countdown() {
	for sec in `seq $1 -1 1`; do
		notify-send -a "Screenshot" -t 1000 -i ~/.config/i3/assets/screenshot.svg "Screenshot" "Taking shot in: $sec"
		sleep 1
	done
}

function ShotNow() {
	
	cd "$dir" || return
	local bytes
	bytes="$(maim -u -o -f png | base64)"
	imgtemp
}

function ShotSelect() {
	
	cd "$dir" || return
	local bytes
	bytes="$(maim -u -o -f png -s -b 2 -c 0.35,0.55,0.85,0.25 -l | base64)"
	imgtemp
}

function Shot10 () {
	countdown '10'
	sleep 1 
	cd "$dir" || return
	local bytes
	bytes="$(maim -u -o -f png | base64)"
	imgtemp
}

if [[ "$1" == "--now" ]]; then
	ShotNow
elif [[ "$1" == "--sel" ]]; then
	ShotSelect
elif [[ "$1" == "--in10" ]]; then
	Shot10
else
	echo -e "Available Options : --now --in10"
fi

exit 0
