#!/usr/bin/env bash

## Copyright (C) 2020-2022 Aditya Shakya <adi1090x@gmail.com>

# Icons
iDIR="$HOME/.config/i3/assets"
notify_app="Volume"

# Get Volume
get_volume() {
	pamixer --get-volume-human | sed 's/%//'
}

# Get icons
get_icon() {
	current="$(get_volume)"
	if [[ "$current" -eq "0" ]]; then
		icon="$iDIR/mute.png"
	elif [[ "$current" == "muted" ]]; then
		icon="$iDIR/mute.png"
	elif [[ ("$current" -ge "0") && ("$current" -le "150") ]]; then
		icon="$iDIR/vol.png"
	fi
}

# Notify
notify_user() {
	notify-send -a "$notify_app" -u low -i "$icon" "Volume" "$(get_volume)%"
}

# Increase Volume
inc_volume() {
	[[ $(pamixer --get-mute) == true ]] && pamixer -u
	pamixer --allow-boost --set-limit 150 -i 5 && get_icon && notify_user
}

# Decrease Volume
dec_volume() {
	[[ $(pamixer --get-mute) == true ]] && pamixer -u
	pamixer --allow-boost --set-limit 150 -d 5 && get_icon && notify_user
}

# Toggle Mute
toggle_mute() {
	if [[ $(pamixer --get-mute) == false ]]; then
		pamixer --toggle-mute && notify-send -a "$notify_app" -u low -i "$iDIR/mute.png" "Volume" "Mute"
	else
		pamixer --toggle-mute && get_icon && notify-send -a "$notify_app" -u low -i "$icon" "Volume" "Unmute"
	fi
}

# Execute accordingly
if [[ -x $(which pamixer) ]]; then
	if [[ "$1" == "--get" ]]; then
		get_volume
	elif [[ "$1" == "--inc" ]]; then
		inc_volume
	elif [[ "$1" == "--dec" ]]; then
		dec_volume
	elif [[ "$1" == "--toggle" ]]; then
		toggle_mute
	else
		echo "$(get_volume)%"
	fi
else
	notify-send -a "$notify_app" -u low "Volume" "'pamixer' is not installed."
fi
