from __future__ import annotations


MATERIAL_ICONS = {
    "grid_view": "\ue9b0",
    "palette": "\ue40a",
    "storefront": "\ue8d1",
    "desktop_windows": "\uefe8",
    "bolt": "\uea0b",
    "music_note": "\ue405",
    "notifications": "\ue7f4",
    "language": "\ue894",
    "restart_alt": "\uf053",
    "shield": "\ue9e0",
    "hub": "\ue9f4",
    "storage": "\ue1db",
    "public": "\ue80b",
    "crop_square": "\ue3c6",
    "widgets": "\ue1bd",
    "menu": "\ue5d2",
    "search": "\ue8b6",
    "close": "\ue5cd",
    "settings": "\ue8b8",
    "photo_library": "\ue413",
    "folder_open": "\ue2c8",
    "auto_awesome": "\ue65f",
    "light_mode": "\ue518",
    "dark_mode": "\ue51c",
    "opacity": "\ue91c",
    "image": "\ue3f4",
    "notifications_active": "\ue7f7",
    "shadow": "\ue9df",
    "tune": "\ue429",
    "sync": "\ue627",
    "calendar_month": "\uebcc",
    "partly_cloudy_day": "\uf172",
    "location_on": "\ue0c8",
    "keyboard": "\ue312",
    "schedule": "\ue8b5",
    "warning": "\ue002",
    "school": "\ue80c",
    "timer": "\ue425",
    "home": "\ue88a",
    "mail": "\ue0be",
    "person": "\ue7fd",
    "lock": "\ue897",
    "refresh": "\ue5d5",
    "calendar_today": "\ue935",
    "contacts": "\ue0ba",
    "rss_feed": "\ue0e5",
    "videocam": "\ue04b",
    "sensors": "\ue51e",
    "show_chart": "\ue6e1",
    "terminal": "\ue31c",
    "watch": "\ue334",
    "sports_esports": "\uea28",
    "open_in_new": "\ue89e",
    "lightbulb": "\ue0f0",
    "toggle_on": "\ue9f6",
    "thermostat": "\ue1ff",
    "device_thermostat": "\ue1ff",
    "window": "\uefe8",
    "mode_fan": "\uf168",
    "water_drop": "\ue798",
    "description": "\ue873",
    "push_pin": "\uef3e",
    "push_pin_outline": "\uf10f",
    "visibility_off": "\ue8f5",
    "add": "\ue145",
    "delete": "\ue872",
}


def material_icon(name: str) -> str:
    return MATERIAL_ICONS.get(name, "?")

